### ISSUE TITLE
Migração de outros códigos

### ISSUE THREAD

**Issue by gildasio** [raulhackerclub/GEEA#1]
Opa!

Vi que tem outros códigos do GEEA, como o que tem lá no [Gitlab](https://gitlab.com/raulhc/GEEA/tree/master/códigos) e em [outra organização](https://github.com/GEEA-RAULHC) aqui no Github. Vocês querem que migre esses códigos para cá? Algo como GEEA-códigos ou GEEA-page?

**Comment by angelobms** [comment]
Ainda não @gjuniioor. Será realizada a organização de outra forma.

**Comment by gildasio** [comment]
Tranquilo, @angelobms , qualquer coisa, só falar! :)
