### ISSUE TITLE
Site do GEEA

### ISSUE THREAD

**Issue by gildasio** [raulhackerclub/GEEA#8]
Vi alí que criou uma pasta chamada `site`. Bem, de acordo com o GithubPages, se criar um branch nesse repositório mesmo, chamado `gh-pages`, o site vai ficar online em raulhackerclub.github.io/GEEA

Olha se não fica melhor para vocês :)

**Comment by angelobms** [comment]
Eu acho interessante que esteja realmente referenciado ao raulhackerclub.github.io. E lá no site do RaulHC colocar um link no projeto para a página do geea (raulhackerclub.github.io/geaa).

**Comment by majurr** [comment]
Concorde @angelobms  e @gjuniioor, fica melhor toda e qualquer iniciativa fazer referência ao hacker space principal.

**Comment by RodolfoSilva** [comment]
Vejam: http://raulhackerclub.github.io/GEEA

Utilizei o template do próprio GitHub.

Vou preparar a migração para o jekyll.

**Comment by gildasio** [comment]
Boa, @RodolfoSilva !! Assim que puder mando um PR de umas possíveis melhorias que tive em mente :)

**Comment by dannyserena** [comment]
Show @RodolfoSilva, está ficando massinha. Agora precisamos selecionar o que iremos colocar no blog.
